/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ict.pwmanager;

import java.sql.Date;
import java.util.List;

import javax.swing.*;

/**
 *
 * @author ict01-16
 */
public class EachDataPanel extends javax.swing.JPanel {

    /**
     * Creates new form EachDataPanel
     */
	SiteVO siteVO;
	String sitekeyString;
	EachDataHandler handler;
	RolloverListener listener;
	PWManager main;
	private final String[] Categorylist = { "±‚∫ª", "∞‘¿”", "¿Ø∆ø∏Æ∆º", "SNS", "±›¿∂" };
    
    public EachDataPanel(SiteVO siteListVO, PWManager main) {
    	initComponents();
    	this.siteVO = siteListVO;
    	sitekeyString = Integer.toString(siteVO.getSitekey());
    	this.main = main;
    	
    	setDataBox(this.siteVO);
    	handler = new EachDataHandler(this, main);
    	listener = new RolloverListener(this, main);
    	this.DataBox.addMouseListener(listener);
    	this.GoWebSite.addActionListener(handler);
    	this.GoWebSite.addMouseListener(listener);
    	this.DeleteData.addActionListener(handler);
    	this.DeleteData.addMouseListener(listener);
    	this.DataBox.addActionListener(handler);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        DataBox = new javax.swing.JButton();
        DeleteData = new javax.swing.JButton();
        GoWebSite = new javax.swing.JButton();

        setBackground(new java.awt.Color(238, 238, 238));
        setPreferredSize(new java.awt.Dimension(370, 70));

        DataBox.setBorderPainted(false);
        DataBox.setBackground(new java.awt.Color(238, 238, 238));
        DataBox.setMargin(new java.awt.Insets(0,0,0,0));
        DataBox.setFont(new java.awt.Font("∏º¿∫ ∞ÌµÒ", 0, 13)); // NOI18N
        DataBox.setText("(ªÁ¿Ã∆Æ∏Ì)\n(ID)");
        DataBox.setHorizontalAlignment(SwingConstants.LEFT); //øﬁ¬ ¡§∑ƒ

        DeleteData.setContentAreaFilled(false);
        DeleteData.setFocusPainted(false);
        DeleteData.setBorderPainted(false);
        DeleteData.setBackground(new java.awt.Color(127,177,224));
        DeleteData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DeleteButton.png")));
        DeleteData.setFont(new java.awt.Font("∏º¿∫ ∞ÌµÒ", 0, 13)); // NOI18N
        
        DeleteData.setMaximumSize(new java.awt.Dimension(40, 40));
        DeleteData.setMinimumSize(new java.awt.Dimension(40, 40));
        DeleteData.setPreferredSize(new java.awt.Dimension(40, 40));
        
        GoWebSite.setMaximumSize(new java.awt.Dimension(40, 40));
        GoWebSite.setMinimumSize(new java.awt.Dimension(40, 40));
        GoWebSite.setPreferredSize(new java.awt.Dimension(40, 40));
        
        GoWebSite.setContentAreaFilled(false);
        GoWebSite.setFocusPainted(false);
        GoWebSite.setBorderPainted(false);
        GoWebSite.setBackground(new java.awt.Color(127,177,224));
        GoWebSite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GoWebButton.png")));
        GoWebSite.setFont(new java.awt.Font("∏º¿∫ ∞ÌµÒ", 0, 13)); // NOI18N
        GoWebSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoWebSiteActionPerformed(evt);
            }
        });
        GoWebSite.setActionCommand(sitekeyString);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(DataBox, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeleteData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GoWebSite)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5,5,5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                		.addComponent(DataBox, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(DeleteData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GoWebSite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5,5,5))
        );

        getAccessibleContext().setAccessibleName("EachDataPanel");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>   
    
    private void GoWebSiteActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }    


    // Variables declaration - do not modify                     
    javax.swing.JButton DataBox;
    javax.swing.JButton DeleteData;
    javax.swing.JButton GoWebSite;
    // End of variables declaration
    
    void setDataBox(SiteVO siteListVO) {
    	if(siteListVO==null) return;
    	
    	String str = "<HTML>" 
    				+ "[" + Categorylist[siteListVO.getCategory()] + "]"
    				+ "ªÁ¿Ã∆Æ∏Ì : " + siteListVO.getSiteName() + "<BR>"
    				+ "∫Òπ–π¯»£ : " + siteListVO.getSitePW() + "</HTML>";
    	
    	DataBox.setText(str);
    }
}
