/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ict.pwmanager;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author even1415
 */
public class SiteAddPanel extends javax.swing.JPanel {

    /**
     * Creates new form SiteAddEditPanel
     */
	PWManager main;
	SiteAddHandler siteAH;
	SiteListPanel siteLP;
	private final String[] Categorylist = { "±âº»", "°ÔÀÓ", "À¯Æ¿¸®Æ¼", "SNS", "±ÝÀ¶" };
	
    public SiteAddPanel(PWManager main) {
        initComponents();
        
        this.main = main;
        
        siteAH = new SiteAddHandler(this, main);
        BackButton.addActionListener(siteAH);
        AddReset.addActionListener(siteAH);
        AddSave.addActionListener(siteAH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        TopBar = new javax.swing.JPanel();
        BackButton = new javax.swing.JButton();
        TopBarText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AddSelectSecurity = new javax.swing.JComboBox<>();
        AddSelectCategory = new javax.swing.JComboBox<>();
        AddReset = new javax.swing.JButton();
        AddSave = new javax.swing.JButton();
        AddSiteName = new HintTextField("»çÀÌÆ®¸í(¸Þ¸ð) ÀÔ·Â"); //new javax.swing.JTextField();
        AddIDText = new HintTextField("¾ÆÀÌµð ÀÔ·Â"); //new javax.swing.JTextField();
        AddPassword = new HintTextField("ºñ¹Ð¹øÈ£ ÀÔ·Â"); //new javax.swing.JTextField();
        AddURL = new HintTextField("»çÀÌÆ® URL ÀÔ·Â"); //new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        guideAddLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(432, 768));
        setPreferredSize(new java.awt.Dimension(432, 768));

        TopBar.setBackground(new java.awt.Color(35, 55, 77));
        TopBar.setPreferredSize(new java.awt.Dimension(400, 60));

        BackButton.setContentAreaFilled(false);
        BackButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        BackButton.setFocusPainted(false);
        BackButton.setBorderPainted(false);
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BackButton.png"))); // NOI18N
        BackButton.setPreferredSize(new java.awt.Dimension(40, 40));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        TopBarText.setFont(new java.awt.Font("¸¼Àº °íµñ", 1, 15)); // NOI18N
        TopBarText.setForeground(new java.awt.Color(238, 238, 238));
        TopBarText.setText("»çÀÌÆ® Ãß°¡");

        javax.swing.GroupLayout TopBarLayout = new javax.swing.GroupLayout(TopBar);
        TopBar.setLayout(TopBarLayout);
        TopBarLayout.setHorizontalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(TopBarText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopBarLayout.setVerticalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBarLayout.createSequentialGroup()
                .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopBarLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TopBarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(TopBarText)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("¸¼Àº °íµñ", 0, 14)); // NOI18N
        jLabel1.setText("»çÀÌÆ®¸í : ");

        jLabel2.setFont(new java.awt.Font("¸¼Àº °íµñ", 0, 14)); // NOI18N
        jLabel2.setText("¾ÆÀÌµð : ");

        jLabel3.setFont(new java.awt.Font("¸¼Àº °íµñ", 0, 14)); // NOI18N
        jLabel3.setText("ºñ¹Ð¹øÈ£ : ");

        jLabel4.setFont(new java.awt.Font("¸¼Àº °íµñ", 0, 14)); // NOI18N
        jLabel4.setText("URL : ");
        

        AddSelectSecurity.setFont(new java.awt.Font("¸¼Àº °íµñ", 0, 11)); // NOI18N
        AddSelectSecurity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "±âº»", "AES", "·£´ý(¹Ì±¸Çö)" }));
        AddSelectSecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEditSelectSecurityActionPerformed(evt);
            }
        });
        
        AddSelectCategory.setFont(new java.awt.Font("¸¼Àº °íµñ", 0, 11)); // NOI18N
        AddSelectCategory.setModel(new javax.swing.DefaultComboBoxModel<>(Categorylist));
        AddSelectCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEditSelectSecurityActionPerformed(evt);
            }
        });

        AddReset.setFont(new java.awt.Font("¸¼Àº °íµñ", 0, 14)); // NOI18N
        AddReset.setText("ÃÊ±âÈ­");
        AddReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEditResetActionPerformed(evt);
            }
        });

        AddSave.setFont(new java.awt.Font("¸¼Àº °íµñ", 0, 14)); // NOI18N
        AddSave.setText("ÀúÀå");

        AddSiteName.setFont(new java.awt.Font("¸¼Àº °íµñ", 0, 12)); // NOI18N
        AddSiteName.setToolTipText("");
        AddSiteName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEditSiteNameActionPerformed(evt);
            }
        });

        AddIDText.setFont(new java.awt.Font("¸¼Àº °íµñ", 0, 12)); // NOI18N
        AddPassword.setFont(new java.awt.Font("¸¼Àº °íµñ", 0, 12)); // NOI18N
        AddURL.setFont(new java.awt.Font("¸¼Àº °íµñ", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("¸¼Àº °íµñ", 0, 14)); // NOI18N
        jLabel5.setText("º¸¾È¹æ½Ä : ");
        
        jLabel6.setFont(new java.awt.Font("¸¼Àº °íµñ", 0, 14)); // NOI18N
        jLabel6.setText("Ä«Å×°í¸® : ");

        guideAddLabel.setFont(new java.awt.Font("¸¼Àº °íµñ", 0, 12)); // NOI18N
        guideAddLabel.setText("ÀÌ °÷¿¡¼­ »çÀÌÆ®¸¦ Ãß°¡ÇÒ ¼ö ÀÖ½À´Ï´Ù.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddReset, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(AddSave, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AddSelectSecurity, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddSelectCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddSiteName, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(AddIDText)
                                    .addComponent(AddPassword)
                                    .addComponent(AddURL)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(guideAddLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guideAddLabel)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(AddSiteName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(AddIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AddPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(AddURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(AddSelectSecurity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(AddSelectCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddReset, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddSave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 80, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) { 
        // TODO add your handling code here:
    }                                          

    private void AddEditSiteNameActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void AddEditSelectSecurityActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void AddEditResetActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            


    // Variables declaration - do not modify
    
    HintTextField AddSiteName;
    HintTextField AddIDText;
    HintTextField AddPassword;
    HintTextField AddURL;
    javax.swing.JComboBox<String> AddSelectSecurity;
    javax.swing.JComboBox<String> AddSelectCategory;
    
    javax.swing.JButton AddReset;
    javax.swing.JButton AddSave;
    
    private javax.swing.JPanel TopBar;
    javax.swing.JLabel TopBarText;
    javax.swing.JButton BackButton;
    javax.swing.JLabel guideAddLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration                   
}
