/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ict.pwmanager;

import java.awt.*;
import java.util.*;
import java.util.List;

import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author even1415
 */
public class SiteListPanel extends javax.swing.JPanel {

    /**
     * Creates new form SiteViewPanel
     */
	ArrayList<EachDataPanel> Each = new ArrayList<EachDataPanel>();
	SiteListHandler siteLH;
	PWManager main;
	int EachDataSize = 0;
	final String[] Categorylist = { "기본", "게임", "유틸리티", "SNS", "금융" };
	EachDataPanel edp;
	
    public SiteListPanel(PWManager main) {
        initComponents();
        this.main = main;
        
        siteLH = new SiteListHandler(this);
        insertEachPanel();

        AddDataButton.addActionListener(siteLH);
        SelectCategory.addActionListener(siteLH);
        BackButton.addActionListener(siteLH);
        
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        AddDataButton = new javax.swing.JButton();
        SelectCategory = new javax.swing.JComboBox<>();
        TopBar = new javax.swing.JPanel();
        BackButton = new javax.swing.JButton();
        TopBarText = new javax.swing.JLabel();
        CauseScroll = new javax.swing.JScrollPane();
        CauseText = new javax.swing.JTextPane();
        DataScrollPane = new javax.swing.JScrollPane(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        DataScrollPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(238, 238, 238));
        setMaximumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(432, 768));

        AddDataButton.setContentAreaFilled(false);
        AddDataButton.setFocusPainted(false);
        AddDataButton.setBorderPainted(false);
        AddDataButton.setBackground(new java.awt.Color(238, 238, 238));
        AddDataButton.setFont(new java.awt.Font("굴림", 1, 36)); // NOI18N
        AddDataButton.setForeground(new java.awt.Color(255, 255, 255));
        //AddDataButton.setText("+");
        AddDataButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AddSiteDataButton.png")));
        AddDataButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        AddDataButton.setMaximumSize(new java.awt.Dimension(60, 60));
        AddDataButton.setMinimumSize(new java.awt.Dimension(60, 60));
        AddDataButton.setPreferredSize(new java.awt.Dimension(60, 60));
        AddDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDataButtonActionPerformed(evt);
            }
        });

        SelectCategory.setFont(new java.awt.Font("맑은 고딕", 0, 11));
        SelectCategory.setModel(new javax.swing.DefaultComboBoxModel<>(Categorylist));
        SelectCategory.setMaximumSize(new java.awt.Dimension(400, 30));
        SelectCategory.setMinimumSize(new java.awt.Dimension(400, 30));
        SelectCategory.setPreferredSize(new java.awt.Dimension(400, 30));
        SelectCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectCategoryActionPerformed(evt);
            }
        });

        TopBar.setBackground(new java.awt.Color(35, 55, 77));
        TopBar.setPreferredSize(new java.awt.Dimension(400, 60));

        BackButton.setContentAreaFilled(false);
        BackButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        BackButton.setFocusPainted(false);
        BackButton.setBorderPainted(false);
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BackButton.png"))); // NOI18N
        BackButton.setPreferredSize(new java.awt.Dimension(40, 40));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        
        TopBarText.setFont(new java.awt.Font("맑은 고딕", 1, 15)); // NOI18N
        TopBarText.setForeground(new java.awt.Color(238, 238, 238));
        TopBarText.setText("사이트 목록");

        javax.swing.GroupLayout TopBarLayout = new javax.swing.GroupLayout(TopBar);
        TopBar.setLayout(TopBarLayout);
        TopBarLayout.setHorizontalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(TopBarText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopBarLayout.setVerticalGroup(
                TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TopBarLayout.createSequentialGroup()
                    .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TopBarLayout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(TopBarLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(TopBarText)))
                    .addContainerGap(15, Short.MAX_VALUE))
       );

        CauseScroll.setPreferredSize(new java.awt.Dimension(300, 50));

        CauseText.setFont(new java.awt.Font("맑은 고딕", 0, 11)); // NOI18N
        CauseText.setText("※주의 : 사이트 이동 시 클립보드에 비밀번호를 자동으로 복사합니다.\n따라서 주기적인 클립보드 비우기를 권장드립니다.\n※클립보드 열기 : [윈도우] + [V] 키 눌러서 [활성화]");
        CauseText.setEnabled(false);
        CauseText.setMaximumSize(new java.awt.Dimension(0, 0));
        CauseText.setMinimumSize(new java.awt.Dimension(0, 0));
        CauseText.setName(""); // NOI18N
        CauseText.setPreferredSize(new java.awt.Dimension(380, 30));
        CauseScroll.setViewportView(CauseText);

        DataScrollPanel.setMaximumSize(new java.awt.Dimension(400, 520));
        DataScrollPanel.setPreferredSize(new Dimension(400,520));
        DataScrollPane.setViewportView(DataScrollPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopBar, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CauseScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DataScrollPane)
                    .addComponent(SelectCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SelectCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DataScrollPane)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddDataButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CauseScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>                        

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void SelectCategoryActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void AddDataButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    public void insertEachPanel() {
    	List<SiteVO> arr = siteLH.siteDao.siteList();
    	Iterator<SiteVO> it = arr.iterator();
    	DataScrollPanel=new JPanel();
    	DataScrollPanel.setMaximumSize(new java.awt.Dimension(400, 520));
        DataScrollPane.setViewportView(DataScrollPanel);
        DataScrollPanel.setLayout(new GridBagLayout());
        
		GridBagConstraints gbc = new GridBagConstraints();
		int num = 0;
		
		gbc.fill = GridBagConstraints.NONE;
		
		gbc.gridx = 0;
		gbc.gridy =0;
		gbc.weighty = 1;
		gbc.anchor = GridBagConstraints.NORTH;
		
		SingletonData singletonData = SingletonData.getSingletonUserData();
	
		while (it.hasNext()) {
			SiteVO svo = it.next();
			edp = new EachDataPanel(svo, main);
			if ((singletonData.getKey()==svo.getKey())
					&& (SelectCategory.getSelectedItem().toString().equals(Categorylist[svo.getCategory()])
					|| SelectCategory.getSelectedItem().toString().equals("기본"))) {
				gbc.gridy = num;
				edp.setDataBox(svo);
				edp.GoWebSite.setActionCommand(svo.getSitekey() + "");
				edp.DeleteData.setActionCommand(svo.getSitekey() + "");
				DataScrollPanel.add(edp, gbc);

				num++;
			}
		}
		//System.out.println("num: "+num);
		if(num<7) { //임의로 패널공간 채우기
			JPanel blank=new JPanel();
			blank.setBackground(new java.awt.Color(238, 238, 238));
			blank.setPreferredSize(new Dimension(370,70*(7-num)));
			gbc.gridy=num+1;
			gbc.weighty=5;
			DataScrollPanel.add(blank, gbc);
		}
		
	}
	/*
수정 버튼에 setActionCommnd("문자열") 로 설정
이때 문자열을 DB의 PK값을 넣어주면
액션 이벤트에서 e.getActionCommand()로 그 값을 알아낼 수 있음
새로고침은 전체 목록 다시한번 호출

조각패널 버튼에 setActionCommand()로 ArrayList의 인덱스값 설정
조각패널 버튼에 Primary Key값을 넣기
그래야 수정 버튼 누르면 해당 버튼의 getActionCommand()값을 얻어다가
DB에서 select해서 가져와서 수정하는 UI폼에 출력이 가능
	*/

    // Variables declaration - do not modify                     
    javax.swing.JButton AddDataButton;
    javax.swing.JButton BackButton;
    javax.swing.JScrollPane CauseScroll;
    javax.swing.JTextPane CauseText;
    javax.swing.JScrollPane DataScrollPane;
    javax.swing.JPanel DataScrollPanel;
    javax.swing.JComboBox<String> SelectCategory;
    javax.swing.JPanel TopBar;
    javax.swing.JLabel TopBarText;
    // End of variables declaration
    

}