/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ict.pwmanager;

/**
 *
 * @author ict01-16
 */
public class EachDataPanel extends javax.swing.JPanel {

    /**
     * Creates new form EachDataPanel
     */
    public EachDataPanel() {
        initComponents();
    }
    
    public EachDataPanel(String str) {
    	super();
    	DataBox.setText(str);
    	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        DataBoxScroll = new javax.swing.JScrollPane();
        DataBox = new javax.swing.JTextPane();
        DeleteData = new javax.swing.JButton();
        GoWebSite = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(370, 100));

        DataBox.setEditable(false);
        DataBox.setText("(사이트명)\n(사이트URL)\n(ID) / ([암호화]비밀번호)");
        DataBoxScroll.setViewportView(DataBox);

        DeleteData.setText("제거");

        GoWebSite.setText("이동");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(DataBoxScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeleteData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GoWebSite)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DataBoxScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(DeleteData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GoWebSite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("EachDataPanel");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JTextPane DataBox;
    private javax.swing.JScrollPane DataBoxScroll;
    private javax.swing.JButton DeleteData;
    private javax.swing.JButton GoWebSite;
    // End of variables declaration                   
}
