create table MEMO (
    IDX NUMBER(4) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    MSG VARCHAR2(100),
    WDATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE MEMO_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

INSERT INTO MEMO(IDX, NAME, MSG)
VALUES(MEMO_SEQ.NEXTVAL, 'È«±æµ¿', '¾È³çÇÏ¼¼¿ä?');

SELECT * FROM MEMO;

COMMIT;
