/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ict.pwmanager;

import java.awt.*;
import java.util.*;

import javax.swing.JButton;

/**
 *
 * @author even1415
 */
public class SiteListPanel extends javax.swing.JPanel {

    /**
     * Creates new form SiteViewPanel
     */
	ArrayList<EachDataPanel> Each = new ArrayList<EachDataPanel>();
	EachDataPanel[] dPanels = new EachDataPanel[4];
	
    public SiteListPanel() {
        initComponents();
        insertEachPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        AddDataButton = new javax.swing.JButton();
        SelectCategory = new javax.swing.JComboBox<>();
        TopBar = new javax.swing.JPanel();
        BackButton = new javax.swing.JButton();
        CauseScroll = new javax.swing.JScrollPane();
        CauseText = new javax.swing.JTextPane();
        DataScrollPane = new javax.swing.JScrollPane();
        DataScrollPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(238, 238, 238));
        setMaximumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(432, 768));

        AddDataButton.setBackground(new java.awt.Color(16, 137, 255));
        AddDataButton.setFont(new java.awt.Font("굴림", 1, 36)); // NOI18N
        AddDataButton.setForeground(new java.awt.Color(255, 255, 255));
        AddDataButton.setText("+");
        AddDataButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        AddDataButton.setMaximumSize(new java.awt.Dimension(60, 60));
        AddDataButton.setMinimumSize(new java.awt.Dimension(60, 60));
        AddDataButton.setPreferredSize(new java.awt.Dimension(60, 60));
        AddDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDataButtonActionPerformed(evt);
            }
        });

        SelectCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "기본그룹", "게임", "유틸리티", "SNS", "금융" }));
        SelectCategory.setMaximumSize(new java.awt.Dimension(400, 30));
        SelectCategory.setMinimumSize(new java.awt.Dimension(400, 30));
        SelectCategory.setPreferredSize(new java.awt.Dimension(400, 30));
        SelectCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectCategoryActionPerformed(evt);
            }
        });

        TopBar.setBackground(new java.awt.Color(35, 55, 77));
        TopBar.setPreferredSize(new java.awt.Dimension(400, 70));

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BackButton.png"))); // NOI18N
        BackButton.setPreferredSize(new java.awt.Dimension(40, 40));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TopBarLayout = new javax.swing.GroupLayout(TopBar);
        TopBar.setLayout(TopBarLayout);
        TopBarLayout.setHorizontalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(377, Short.MAX_VALUE))
        );
        TopBarLayout.setVerticalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        CauseScroll.setPreferredSize(new java.awt.Dimension(300, 50));

        CauseText.setText("※주의 : 사이트 이동 시 클립보드에 비밀번호를 자동으로 복사합니다.\n따라서 주기적인 클립보드 비우기를 권장드립니다.\n※클립보드 열기 : [윈도우] + [V] 키 눌러서 [활성화]");
        CauseText.setEnabled(false);
        CauseText.setMaximumSize(new java.awt.Dimension(0, 0));
        CauseText.setMinimumSize(new java.awt.Dimension(0, 0));
        CauseText.setName(""); // NOI18N
        CauseText.setPreferredSize(new java.awt.Dimension(380, 30));
        CauseScroll.setViewportView(CauseText);

        DataScrollPanel.setMaximumSize(new java.awt.Dimension(400, 520));

        DataScrollPane.setViewportView(DataScrollPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopBar, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CauseScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DataScrollPane)
                    .addComponent(SelectCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SelectCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DataScrollPane)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddDataButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CauseScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>                        

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void SelectCategoryActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void AddDataButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

private void insertEachPanel() {
        DataScrollPanel.setLayout(new GridBagLayout());
        
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.VERTICAL;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.gridx = GridBagConstraints.BOTH;
        gbc.anchor = GridBagConstraints.PAGE_START;
        
        for(int i=0; i<10; i++) { //Each.size()
        	gbc.gridy = i+1;
        	
        	//dPanels[i] = new EachDataPanel();
        	//DataScrollPanel.add(dPanels[i], gbc);
        	Each.add(new EachDataPanel());
        	DataScrollPanel.add(Each.get(i), gbc);
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton AddDataButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JScrollPane CauseScroll;
    private javax.swing.JTextPane CauseText;
    private javax.swing.JScrollPane DataScrollPane;
    private javax.swing.JPanel DataScrollPanel;
    private javax.swing.JComboBox<String> SelectCategory;
    private javax.swing.JPanel TopBar;
    // End of variables declaration                   

}